### ISSUE TITLE
error runing

### ISSUE THREAD

**Issue by Mendim** [febLey/counter-strike_server#2]
root@scw-nostalgic-ganguly:~# docker run --name counter-strike_server -p 27015:27015/udp -p 27015:27015 counter-strike_server
I get this error

```
Unable to find image 'counter-strike_server:latest' locally
docker: Error response from daemon: pull access denied for counter-strike_server, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
```

**Comment by febLey** [comment]
I'll have a look at it this weekend.
Thanks for reporting.

**Comment by febLey** [comment]
The solution is quiet simple, I wrote the wrong command into the README.md.
Just try this:

```
docker run --name counter-strike_server -p 27015:27015/udp -p 27015:27015 febley/counter-strike_server:latest
```

Does it work for you now?

**Comment by Mendim** [comment]
Ok how i can add new map to this.can we know where the location is located.and how I can login as admin to manage the server.thank you

**Comment by febLey** [comment]
I recommend you to run this via the `docker-compose` command.
https://github.com/febLey/counter-strike_server#docker-compose

The other settings can be done via the `server.cfg`. Have a look at the `README.md` (rcon_password).
I'm not sure how you add custom maps, but I think you can create a local folder which contains your custom maps and link it as volume to the path `/hlds/cstrike/maps`.
You can create a map list of existing maps via the `mapcycle.txt`.
